In [2]:
from keras.models import Sequential
from keras.layers import Dense, Activation

D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
model = Sequential([
    Dense(32, input_shape=(27,)),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])

In [4]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [7]:
import numpy as np

In [8]:
import read
data, no_act, map_act = read.readData()

In [150]:
print(data)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
print(no_act)

{'Bed_to_toilet': 30, 'Breakfast': 48, 'Bed': 207, 'C_work': 46, 'Dinner': 42, 'Laundry': 10, 'Leave_home': 69, 'Lunch': 37, 'Night_wandering': 67, 'R_medicine': 44}


In [15]:
input = np.array(X_train)

In [16]:
print(input.shape)

(600, 27)


In [17]:
X_data  = []
X_label = []
for key, value in map_act.items():
    for j in range(no_act[value]):
        X_data.append(data[value][j])
        X_label.append(key)

In [18]:
input_data = np.array(X_data)
input_label = np.array(X_label)

In [20]:
import keras

In [21]:
label = keras.utils.to_categorical(input_label, num_classes=10)

In [22]:
model.fit(input_data, label, epochs=10, batch_size=32)

Epoch 1/10
600/600 [==============================] - 0s 401us/step - loss: 4.9507 - acc: 0.2033
Epoch 2/10
600/600 [==============================] - 0s 40us/step - loss: 3.9247 - acc: 0.3950
Epoch 3/10
600/600 [==============================] - 0s 40us/step - loss: 3.5127 - acc: 0.5017
Epoch 4/10
600/600 [==============================] - 0s 40us/step - loss: 3.1992 - acc: 0.5750
Epoch 5/10
600/600 [==============================] - 0s 53us/step - loss: 2.9947 - acc: 0.6083
Epoch 6/10
600/600 [==============================] - 0s 47us/step - loss: 2.7619 - acc: 0.6383
Epoch 7/10
600/600 [==============================] - 0s 47us/step - loss: 2.2954 - acc: 0.6433
Epoch 8/10
600/600 [==============================] - 0s 47us/step - loss: 2.1214 - acc: 0.6733
Epoch 9/10
600/600 [==============================] - 0s 40us/step - loss: 1.9981 - acc: 0.6900
Epoch 10/10
600/600 [==============================] - 0s 40us/step - loss: 1.9217 - acc: 0.7050


In [23]:
model.fit(input_data, label, epochs=20, batch_size=32)

Epoch 1/20
600/600 [==============================] - 0s 53us/step - loss: 1.8246 - acc: 0.7217
Epoch 2/20
600/600 [==============================] - 0s 40us/step - loss: 1.8150 - acc: 0.7433
Epoch 3/20
600/600 [==============================] - 0s 40us/step - loss: 1.7248 - acc: 0.7533
Epoch 4/20
600/600 [==============================] - 0s 40us/step - loss: 1.7015 - acc: 0.7600
Epoch 5/20
600/600 [==============================] - 0s 47us/step - loss: 1.6540 - acc: 0.7800
Epoch 6/20
600/600 [==============================] - 0s 47us/step - loss: 1.6521 - acc: 0.7733
Epoch 7/20
600/600 [==============================] - 0s 47us/step - loss: 1.6254 - acc: 0.7817
Epoch 8/20
600/600 [==============================] - 0s 40us/step - loss: 1.5935 - acc: 0.7833
Epoch 9/20
600/600 [==============================] - 0s 47us/step - loss: 1.5721 - acc: 0.8000
Epoch 10/20
600/600 [==============================] - 0s 47us/step - loss: 1.5835 - acc: 0.7883
Epoch 11/20
600/600 [==================

In [24]:
model.fit(input_data, label, epochs=20, batch_size=2)

Epoch 1/20
600/600 [==============================] - 0s 501us/step - loss: 1.5170 - acc: 0.7933
Epoch 2/20
600/600 [==============================] - 0s 491us/step - loss: 1.5310 - acc: 0.7950
Epoch 3/20
600/600 [==============================] - 0s 468us/step - loss: 1.5354 - acc: 0.7917
Epoch 4/20
600/600 [==============================] - 0s 484us/step - loss: 1.5114 - acc: 0.8000
Epoch 5/20
600/600 [==============================] - 0s 547us/step - loss: 1.5010 - acc: 0.7933
Epoch 6/20
600/600 [==============================] - 0s 507us/step - loss: 1.4919 - acc: 0.8017
Epoch 7/20
600/600 [==============================] - 0s 540us/step - loss: 1.5191 - acc: 0.7983
Epoch 8/20
600/600 [==============================] - 0s 447us/step - loss: 1.4996 - acc: 0.8033
Epoch 9/20
600/600 [==============================] - 0s 478us/step - loss: 1.5127 - acc: 0.8083
Epoch 10/20
600/600 [==============================] - 0s 483us/step - loss: 1.5115 - acc: 0.8033
Epoch 11/20
600/600 [========

In [28]:
model.fit(input_data, label, epochs=20, batch_size=2, validation_split=0.3)

Train on 420 samples, validate on 180 samples
Epoch 1/20
420/420 [==============================] - 1s 1ms/step - loss: 1.7901 - acc: 0.8357 - val_loss: 3.4957 - val_acc: 0.4889
Epoch 2/20
420/420 [==============================] - 0s 556us/step - loss: 1.7457 - acc: 0.8500 - val_loss: 5.7103 - val_acc: 0.3611
Epoch 3/20
420/420 [==============================] - 0s 596us/step - loss: 1.7297 - acc: 0.8476 - val_loss: 7.0165 - val_acc: 0.3500
Epoch 4/20
420/420 [==============================] - 0s 568us/step - loss: 1.7254 - acc: 0.8500 - val_loss: 7.8630 - val_acc: 0.2944
Epoch 5/20
420/420 [==============================] - 0s 557us/step - loss: 1.7272 - acc: 0.8595 - val_loss: 8.4486 - val_acc: 0.2500
Epoch 6/20
420/420 [==============================] - 0s 520us/step - loss: 1.7124 - acc: 0.8548 - val_loss: 9.0826 - val_acc: 0.2389
Epoch 7/20
420/420 [==============================] - 0s 585us/step - loss: 1.7217 - acc: 0.8524 - val_loss: 9.4954 - val_acc: 0.2333
Epoch 8/20
420/420

In [29]:
model.fit(input_data, label, epochs=20, batch_size=2, validation_split=0.5)

Train on 300 samples, validate on 300 samples
Epoch 1/20
300/300 [==============================] - 0s 707us/step - loss: 0.1013 - acc: 0.9633 - val_loss: 9.1953 - val_acc: 0.3700
Epoch 2/20
300/300 [==============================] - 0s 575us/step - loss: 0.0971 - acc: 0.9667 - val_loss: 9.2588 - val_acc: 0.3633
Epoch 3/20
300/300 [==============================] - 0s 652us/step - loss: 0.0907 - acc: 0.9733 - val_loss: 9.3226 - val_acc: 0.3600
Epoch 4/20
300/300 [==============================] - 0s 672us/step - loss: 0.0895 - acc: 0.9633 - val_loss: 9.3700 - val_acc: 0.3600
Epoch 5/20
300/300 [==============================] - 0s 689us/step - loss: 0.0860 - acc: 0.9700 - val_loss: 9.4066 - val_acc: 0.3600
Epoch 6/20
300/300 [==============================] - 0s 699us/step - loss: 0.0859 - acc: 0.9733 - val_loss: 9.4805 - val_acc: 0.3567
Epoch 7/20
300/300 [==============================] - 0s 627us/step - loss: 0.0841 - acc: 0.9667 - val_loss: 9.5079 - val_acc: 0.3567
Epoch 8/20
300/3

In [31]:
model.evaluate(x=input_data, y=label, batch_size=2, verbose=1, sample_weight=None)

600/600 [==============================] - 0s 213us/step


[5.007782051547935, 0.6616666666666666]

In [33]:
model.evaluate(x=input_data, y=label, batch_size=None, verbose=1, sample_weight=None, steps=10)

10/10 [==============================] - 0s 2ms/step


[5.00778341293335, 0.6616666913032532]

In [35]:
data_0  = []
label_0 = []
for j in range(no_act[map_act[0]]):
    X_data.append(data[map_act[0]][j])
    X_label.append(0)

In [36]:
input_data_0 = np.array(data_0)
input_label_0 = np.array(label_0)

In [39]:
input_data_0.shape

(0,)

In [40]:
print(input_data_0)

[]


In [41]:
data_0  = []
label_0 = []
for j in range(no_act[map_act[0]]):
    data_0.append(data[map_act[0]][j])
    label_0.append(0)

In [43]:
input_label_0 = keras.utils.to_categorical(input_label_0, 10)

In [44]:
input_data_0 = np.array(data_0)
input_label_0 = np.array(label_0)
input_label_0 = keras.utils.to_categorical(input_label_0, 10)
model.evaluate(input_data_0, input_label_0, batch_size=32, verbose=1)

30/30 [==============================] - 0s 200us/step


[0.19742900133132935, 0.9333333373069763]

In [45]:
data_0  = []
label_0 = []
for j in range(no_act[map_act[1]]):
    data_0.append(data[map_act[1]][j])
    label_0.append(1)
input_data_0 = np.array(data_0)
input_label_0 = np.array(label_0)
input_label_0 = keras.utils.to_categorical(input_label_0, 10)
model.evaluate(input_data_0, input_label_0, batch_size=32, verbose=1)

48/48 [==============================] - 0s 167us/step


[0.0012851220089942217, 1.0]

In [46]:
data_0  = []
label_0 = []
for j in range(no_act[map_act[2]]):
    data_0.append(data[map_act[2]][j])
    label_0.append(2)
input_data_0 = np.array(data_0)
input_label_0 = np.array(label_0)
input_label_0 = keras.utils.to_categorical(input_label_0, 10)
model.evaluate(input_data_0, input_label_0, batch_size=32, verbose=1)

207/207 [==============================] - 0s 58us/step


[0.06819862979441738, 0.966183574879227]

In [47]:
data_0  = []
label_0 = []
for j in range(no_act[map_act[3]]):
    data_0.append(data[map_act[3]][j])
    label_0.append(3)
input_data_0 = np.array(data_0)
input_label_0 = np.array(label_0)
input_label_0 = keras.utils.to_categorical(input_label_0, 10)
model.evaluate(input_data_0, input_label_0, batch_size=32, verbose=1)

46/46 [==============================] - 0s 283us/step


[0.8512253553971, 0.9130434808523759]

In [48]:
data_0  = []
label_0 = []
for j in range(no_act[map_act[4]]):
    data_0.append(data[map_act[4]][j])
    label_0.append(2)
input_data_0 = np.array(data_0)
input_label_0 = np.array(label_0)
input_label_0 = keras.utils.to_categorical(input_label_0, 10)
model.evaluate(input_data_0, input_label_0, batch_size=32, verbose=1)

42/42 [==============================] - 0s 143us/step


[16.11809539794922, 0.0]

In [49]:
data_0  = []
label_0 = []
for j in range(no_act[map_act[4]]):
    data_0.append(data[map_act[4]][j])
    label_0.append(4)
input_data_0 = np.array(data_0)
input_label_0 = np.array(label_0)
input_label_0 = keras.utils.to_categorical(input_label_0, 10)
model.evaluate(input_data_0, input_label_0, batch_size=32, verbose=1)

42/42 [==============================] - 0s 167us/step


[16.11809539794922, 0.0]

In [50]:
data_0  = []
label_0 = []
for j in range(no_act[map_act[5]]):
    data_0.append(data[map_act[5]][j])
    label_0.append(5)
input_data_0 = np.array(data_0)
input_label_0 = np.array(label_0)
input_label_0 = keras.utils.to_categorical(input_label_0, 10)
model.evaluate(input_data_0, input_label_0, batch_size=32, verbose=1)

10/10 [==============================] - 0s 100us/step


[0.06586682051420212, 1.0]

In [51]:
data_0  = []
label_0 = []
for j in range(no_act[map_act[6]]):
    data_0.append(data[map_act[6]][j])
    label_0.append(6)
input_data_0 = np.array(data_0)
input_label_0 = np.array(label_0)
input_label_0 = keras.utils.to_categorical(input_label_0, 10)
model.evaluate(input_data_0, input_label_0, batch_size=32, verbose=1)

69/69 [==============================] - 0s 102us/step


[0.002007307132362916, 1.0]

In [52]:
data_0  = []
label_0 = []
for j in range(no_act[map_act[7]]):
    data_0.append(data[map_act[7]][j])
    label_0.append(7)
input_data_0 = np.array(data_0)
input_label_0 = np.array(label_0)
input_label_0 = keras.utils.to_categorical(input_label_0, 10)
model.evaluate(input_data_0, input_label_0, batch_size=32, verbose=1)

37/37 [==============================] - 0s 108us/step


[16.11809539794922, 0.0]

In [53]:
data_0  = []
label_0 = []
for j in range(no_act[map_act[8]]):
    data_0.append(data[map_act[8]][j])
    label_0.append(8)
input_data_0 = np.array(data_0)
input_label_0 = np.array(label_0)
input_label_0 = keras.utils.to_categorical(input_label_0, 10)
model.evaluate(input_data_0, input_label_0, batch_size=32, verbose=1)

67/67 [==============================] - 0s 75us/step


[16.115845295920302, 0.0]

In [54]:
data_0  = []
label_0 = []
for j in range(no_act[map_act[9]]):
    data_0.append(data[map_act[9]][j])
    label_0.append(9)
input_data_0 = np.array(data_0)
input_label_0 = np.array(label_0)
input_label_0 = keras.utils.to_categorical(input_label_0, 10)
model.evaluate(input_data_0, input_label_0, batch_size=32, verbose=1)

44/44 [==============================] - 0s 114us/step


[13.443702004172586, 0.0]

In [55]:
import importlib

In [57]:
importlib.reload(read)

<module 'read' from 'C:\\Users\\Jay\\Desktop\\capstone\\read.py'>

In [61]:
importlib.reload(read)

TabError: inconsistent use of tabs and spaces in indentation (read.py, line 82)

In [62]:
importlib.reload(read)

TabError: inconsistent use of tabs and spaces in indentation (read.py, line 82)

In [63]:
importlib.reload(read)

TabError: inconsistent use of tabs and spaces in indentation (read.py, line 82)

In [64]:
importlib.reload(read)

TabError: inconsistent use of tabs and spaces in indentation (read.py, line 82)

In [65]:
importlib.reload(read.py)

AttributeError: module 'read' has no attribute 'py'

In [66]:
importlib.reload(read)

TabError: inconsistent use of tabs and spaces in indentation (read.py, line 81)

In [67]:
importlib.reload(read)

TabError: inconsistent use of tabs and spaces in indentation (read.py, line 83)

In [68]:
importlib.reload(read)

TabError: inconsistent use of tabs and spaces in indentation (read.py, line 83)

In [69]:
importlib.reload(read)

TabError: inconsistent use of tabs and spaces in indentation (read.py, line 86)

In [70]:
importlib.reload(read)

TabError: inconsistent use of tabs and spaces in indentation (read.py, line 86)

In [71]:
importlib.reload(read)

TabError: inconsistent use of tabs and spaces in indentation (read.py, line 86)

In [79]:
importlib.reload(read)

<module 'read' from 'C:\\Users\\Jay\\Desktop\\capstone\\read.py'>

In [80]:
data, label = read.readData()

In [74]:
import numpy as np

In [77]:
data, label =read.readData()

NameError: name 'np' is not defined

In [76]:
np.array([1])

array([1])

In [78]:
data, label =read.readData()

NameError: name 'np' is not defined

In [81]:
print(data)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [82]:
data.size

16200

In [83]:
data[0].size

27

In [84]:
16200/27

600.0

In [85]:
data1 = data

In [86]:
import process

SyntaxError: invalid syntax (process.py, line 16)

In [146]:
importlib.reload(process)

<module 'process' from 'C:\\Users\\Jay\\Desktop\\capstone\\process.py'>

In [124]:
data = process.normalization(data)

old:1


TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U11') dtype('<U11') dtype('<U11')

In [103]:
print(data[1])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [110]:
test = 

In [148]:
result = process.normalization(test)

3.0
4.0
5.0
6.0


In [147]:
test = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

In [149]:
print(result)

[[0.33333333 0.5        0.6        0.66666667]
 [0.66666667 0.75       0.8        0.83333333]
 [1.         1.         1.         1.        ]]


In [130]:
test

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1]])

In [131]:
print(type(test))

<class 'numpy.ndarray'>
