In [1]:
import read

In [2]:
import process
import numpy as np

In [3]:
data, label = read.readData()

In [5]:
data = process.normalization(data)

134.0
26.0
39.0
30.0
88.0
28.0
34.0
46.0
54.0
34.0
86.0
80.0
94.0
65.0
41.0
47.0
93.0
179.0
17.0
107.0
239.0
165.0
148.0
303.0
9.0
89.0
9.0


In [6]:
print(data[0])

[0.         0.         0.         0.         0.09090909 0.
 0.05882353 0.04347826 0.12962963 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.        ]


In [7]:
from keras.models import Sequential
from keras.layers import Dense, Activation

D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [8]:
model = Sequential([
    Dense(32, input_shape=(27,)),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [10]:
import keras
label = keras.utils.to_categorical(label, num_classes=10)

In [11]:
model.fit(data, label, epochs=10, batch_size=32)

Epoch 1/10
600/600 [==============================] - 0s 342us/step - loss: 2.2255 - acc: 0.3283
Epoch 2/10
600/600 [==============================] - 0s 68us/step - loss: 2.1354 - acc: 0.3450
Epoch 3/10
600/600 [==============================] - 0s 48us/step - loss: 2.0518 - acc: 0.3467
Epoch 4/10
600/600 [==============================] - 0s 67us/step - loss: 1.9650 - acc: 0.3600
Epoch 5/10
600/600 [==============================] - 0s 68us/step - loss: 1.8833 - acc: 0.3717
Epoch 6/10
600/600 [==============================] - 0s 68us/step - loss: 1.8104 - acc: 0.3833
Epoch 7/10
600/600 [==============================] - 0s 83us/step - loss: 1.7470 - acc: 0.4017
Epoch 8/10
600/600 [==============================] - 0s 60us/step - loss: 1.6896 - acc: 0.4050
Epoch 9/10
600/600 [==============================] - 0s 67us/step - loss: 1.6382 - acc: 0.4100
Epoch 10/10
600/600 [==============================] - 0s 85us/step - loss: 1.5900 - acc: 0.4117


In [13]:
model.fit(data, label, epochs=20, batch_size=32)

Epoch 1/20
600/600 [==============================] - 0s 63us/step - loss: 1.5454 - acc: 0.4183
Epoch 2/20
600/600 [==============================] - 0s 52us/step - loss: 1.5052 - acc: 0.4267
Epoch 3/20
600/600 [==============================] - 0s 43us/step - loss: 1.4693 - acc: 0.4383
Epoch 4/20
600/600 [==============================] - 0s 43us/step - loss: 1.4365 - acc: 0.4417
Epoch 5/20
600/600 [==============================] - 0s 53us/step - loss: 1.4059 - acc: 0.4467
Epoch 6/20
600/600 [==============================] - 0s 60us/step - loss: 1.3765 - acc: 0.4583
Epoch 7/20
600/600 [==============================] - 0s 77us/step - loss: 1.3495 - acc: 0.4600
Epoch 8/20
600/600 [==============================] - 0s 62us/step - loss: 1.3242 - acc: 0.4850
Epoch 9/20
600/600 [==============================] - 0s 72us/step - loss: 1.3006 - acc: 0.5067
Epoch 10/20
600/600 [==============================] - 0s 63us/step - loss: 1.2772 - acc: 0.5567
Epoch 11/20
600/600 [==================

In [14]:
model.fit(data, label, epochs=30, batch_size=32)

Epoch 1/30
600/600 [==============================] - 0s 57us/step - loss: 1.0748 - acc: 0.6383
Epoch 2/30
600/600 [==============================] - 0s 45us/step - loss: 1.0598 - acc: 0.6367
Epoch 3/30
600/600 [==============================] - 0s 55us/step - loss: 1.0450 - acc: 0.6383
Epoch 4/30
600/600 [==============================] - 0s 38us/step - loss: 1.0309 - acc: 0.6367
Epoch 5/30
600/600 [==============================] - 0s 63us/step - loss: 1.0173 - acc: 0.6467
Epoch 6/30
600/600 [==============================] - 0s 72us/step - loss: 1.0036 - acc: 0.6517
Epoch 7/30
600/600 [==============================] - 0s 68us/step - loss: 0.9904 - acc: 0.6533
Epoch 8/30
600/600 [==============================] - 0s 63us/step - loss: 0.9778 - acc: 0.6650
Epoch 9/30
600/600 [==============================] - 0s 57us/step - loss: 0.9655 - acc: 0.6717
Epoch 10/30
600/600 [==============================] - 0s 57us/step - loss: 0.9535 - acc: 0.6767
Epoch 11/30
600/600 [==================

In [15]:
model.fit(data, label, epochs=40, batch_size=32)

Epoch 1/40
600/600 [==============================] - 0s 58us/step - loss: 0.7718 - acc: 0.7633
Epoch 2/40
600/600 [==============================] - 0s 45us/step - loss: 0.7651 - acc: 0.7683
Epoch 3/40
600/600 [==============================] - 0s 42us/step - loss: 0.7578 - acc: 0.7667
Epoch 4/40
600/600 [==============================] - 0s 40us/step - loss: 0.7529 - acc: 0.7767
Epoch 5/40
600/600 [==============================] - 0s 45us/step - loss: 0.7466 - acc: 0.7700
Epoch 6/40
600/600 [==============================] - 0s 65us/step - loss: 0.7416 - acc: 0.7683
Epoch 7/40
600/600 [==============================] - 0s 67us/step - loss: 0.7355 - acc: 0.7700
Epoch 8/40
600/600 [==============================] - 0s 63us/step - loss: 0.7305 - acc: 0.7717
Epoch 9/40
600/600 [==============================] - 0s 55us/step - loss: 0.7244 - acc: 0.7733
Epoch 10/40
600/600 [==============================] - 0s 57us/step - loss: 0.7199 - acc: 0.7717
Epoch 11/40
600/600 [==================

In [16]:
model.fit(data, label, epochs=50, batch_size=32)

Epoch 1/50
600/600 [==============================] - 0s 57us/step - loss: 0.6054 - acc: 0.7917
Epoch 2/50
600/600 [==============================] - 0s 45us/step - loss: 0.6037 - acc: 0.7867
Epoch 3/50
600/600 [==============================] - 0s 42us/step - loss: 0.6000 - acc: 0.7900
Epoch 4/50
600/600 [==============================] - 0s 50us/step - loss: 0.5972 - acc: 0.7917
Epoch 5/50
600/600 [==============================] - 0s 45us/step - loss: 0.5948 - acc: 0.7883
Epoch 6/50
600/600 [==============================] - 0s 50us/step - loss: 0.5924 - acc: 0.7917
Epoch 7/50
600/600 [==============================] - 0s 50us/step - loss: 0.5908 - acc: 0.7900
Epoch 8/50
600/600 [==============================] - 0s 62us/step - loss: 0.5877 - acc: 0.7933
Epoch 9/50
600/600 [==============================] - 0s 70us/step - loss: 0.5860 - acc: 0.7917
Epoch 10/50
600/600 [==============================] - 0s 60us/step - loss: 0.5827 - acc: 0.7883
Epoch 11/50
600/600 [==================

In [17]:
model.fit(data, label, epochs=20, batch_size=32)

Epoch 1/20
600/600 [==============================] - 0s 58us/step - loss: 0.5093 - acc: 0.8250
Epoch 2/20
600/600 [==============================] - 0s 47us/step - loss: 0.5073 - acc: 0.8217
Epoch 3/20
600/600 [==============================] - 0s 42us/step - loss: 0.5052 - acc: 0.8233
Epoch 4/20
600/600 [==============================] - 0s 40us/step - loss: 0.5049 - acc: 0.8217
Epoch 5/20
600/600 [==============================] - 0s 47us/step - loss: 0.5032 - acc: 0.8217
Epoch 6/20
600/600 [==============================] - 0s 58us/step - loss: 0.5017 - acc: 0.8200
Epoch 7/20
600/600 [==============================] - 0s 48us/step - loss: 0.4999 - acc: 0.8250
Epoch 8/20
600/600 [==============================] - 0s 63us/step - loss: 0.4991 - acc: 0.8283
Epoch 9/20
600/600 [==============================] - 0s 62us/step - loss: 0.4973 - acc: 0.8300
Epoch 10/20
600/600 [==============================] - 0s 73us/step - loss: 0.4956 - acc: 0.8183
Epoch 11/20
600/600 [==================

In [18]:
data, label = read.readData()
label = keras.utils.to_categorical(label, num_classes=10)

In [20]:
# Train on raw data
model.fit(data, label, epochs=50, batch_size=32)

Epoch 1/50
600/600 [==============================] - 0s 57us/step - loss: 5.5782 - acc: 0.6333
Epoch 2/50
600/600 [==============================] - 0s 42us/step - loss: 5.5096 - acc: 0.6350
Epoch 3/50
600/600 [==============================] - 0s 50us/step - loss: 5.4307 - acc: 0.6467
Epoch 4/50
600/600 [==============================] - 0s 67us/step - loss: 5.4104 - acc: 0.6400
Epoch 5/50
600/600 [==============================] - 0s 55us/step - loss: 5.3030 - acc: 0.6383
Epoch 6/50
600/600 [==============================] - 0s 55us/step - loss: 5.2119 - acc: 0.6500
Epoch 7/50
600/600 [==============================] - 0s 50us/step - loss: 5.0176 - acc: 0.6450
Epoch 8/50
600/600 [==============================] - 0s 58us/step - loss: 4.7286 - acc: 0.6483
Epoch 9/50
600/600 [==============================] - 0s 62us/step - loss: 4.6332 - acc: 0.6533
Epoch 10/50
600/600 [==============================] - 0s 70us/step - loss: 4.5899 - acc: 0.6600
Epoch 11/50
600/600 [==================

In [21]:
model.fit(data, label, epochs=50, batch_size=32)

Epoch 1/50
600/600 [==============================] - 0s 60us/step - loss: 3.6613 - acc: 0.7233
Epoch 2/50
600/600 [==============================] - 0s 42us/step - loss: 3.7067 - acc: 0.7167
Epoch 3/50
600/600 [==============================] - 0s 43us/step - loss: 3.7058 - acc: 0.7333
Epoch 4/50
600/600 [==============================] - 0s 40us/step - loss: 3.6780 - acc: 0.7250
Epoch 5/50
600/600 [==============================] - 0s 45us/step - loss: 3.6615 - acc: 0.7133
Epoch 6/50
600/600 [==============================] - 0s 47us/step - loss: 3.6611 - acc: 0.7350
Epoch 7/50
600/600 [==============================] - 0s 60us/step - loss: 3.7059 - acc: 0.7300
Epoch 8/50
600/600 [==============================] - 0s 53us/step - loss: 3.6371 - acc: 0.7367
Epoch 9/50
600/600 [==============================] - 0s 65us/step - loss: 3.6692 - acc: 0.7317
Epoch 10/50
600/600 [==============================] - 0s 57us/step - loss: 3.6252 - acc: 0.7400
Epoch 11/50
600/600 [==================

In [22]:
model.fit(data, label, epochs=50, batch_size=32)

Epoch 1/50
600/600 [==============================] - 0s 53us/step - loss: 3.2726 - acc: 0.7500
Epoch 2/50
600/600 [==============================] - 0s 43us/step - loss: 3.3014 - acc: 0.7450
Epoch 3/50
600/600 [==============================] - 0s 42us/step - loss: 3.2293 - acc: 0.7500
Epoch 4/50
600/600 [==============================] - 0s 42us/step - loss: 3.2058 - acc: 0.7517
Epoch 5/50
600/600 [==============================] - 0s 47us/step - loss: 3.2653 - acc: 0.7500
Epoch 6/50
600/600 [==============================] - 0s 62us/step - loss: 3.2370 - acc: 0.7450
Epoch 7/50
600/600 [==============================] - 0s 65us/step - loss: 3.2463 - acc: 0.7433
Epoch 8/50
600/600 [==============================] - 0s 55us/step - loss: 3.2048 - acc: 0.7467
Epoch 9/50
600/600 [==============================] - 0s 48us/step - loss: 3.1919 - acc: 0.7500
Epoch 10/50
600/600 [==============================] - 0s 60us/step - loss: 3.2156 - acc: 0.7533
Epoch 11/50
600/600 [==================

In [23]:
model2 = Sequential([
    Dense(32, input_shape=(27,)),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])
model2.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [24]:
# Train on raw data
model.fit(data, label, epochs=50, batch_size=32)

Epoch 1/50
600/600 [==============================] - 0s 173us/step - loss: 2.9902 - acc: 0.7583
Epoch 2/50
600/600 [==============================] - 0s 60us/step - loss: 2.9885 - acc: 0.7617
Epoch 3/50
600/600 [==============================] - 0s 65us/step - loss: 2.9598 - acc: 0.7550
Epoch 4/50
600/600 [==============================] - 0s 60us/step - loss: 2.9698 - acc: 0.7583
Epoch 5/50
600/600 [==============================] - 0s 57us/step - loss: 2.9764 - acc: 0.7567
Epoch 6/50
600/600 [==============================] - 0s 47us/step - loss: 2.9476 - acc: 0.7667
Epoch 7/50
600/600 [==============================] - 0s 48us/step - loss: 3.0004 - acc: 0.7633
Epoch 8/50
600/600 [==============================] - 0s 63us/step - loss: 2.9574 - acc: 0.7667
Epoch 9/50
600/600 [==============================] - 0s 58us/step - loss: 2.9332 - acc: 0.7650
Epoch 10/50
600/600 [==============================] - 0s 67us/step - loss: 2.9579 - acc: 0.7583
Epoch 11/50
600/600 [=================

In [25]:
# Train on raw data
model.fit(data, label, epochs=50, batch_size=32)

Epoch 1/50
600/600 [==============================] - 0s 58us/step - loss: 2.8504 - acc: 0.7783
Epoch 2/50
600/600 [==============================] - 0s 37us/step - loss: 2.8734 - acc: 0.7700
Epoch 3/50
600/600 [==============================] - 0s 40us/step - loss: 2.8393 - acc: 0.7783
Epoch 4/50
600/600 [==============================] - 0s 38us/step - loss: 2.8416 - acc: 0.7733
Epoch 5/50
600/600 [==============================] - 0s 45us/step - loss: 2.8378 - acc: 0.7833
Epoch 6/50
600/600 [==============================] - 0s 38us/step - loss: 2.8405 - acc: 0.7800
Epoch 7/50
600/600 [==============================] - 0s 58us/step - loss: 2.8477 - acc: 0.7767
Epoch 8/50
600/600 [==============================] - 0s 45us/step - loss: 2.8529 - acc: 0.7717
Epoch 9/50
600/600 [==============================] - 0s 57us/step - loss: 2.8353 - acc: 0.7850
Epoch 10/50
600/600 [==============================] - 0s 62us/step - loss: 2.8230 - acc: 0.7883
Epoch 11/50
600/600 [==================

In [39]:
print(label[598])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [32]:
model.predict(data)

array([[4.7723243e-01, 0.0000000e+00, 5.2276748e-01, ..., 0.0000000e+00,
        1.4090732e-07, 0.0000000e+00],
       [4.7998691e-01, 0.0000000e+00, 5.1998836e-01, ..., 0.0000000e+00,
        2.4720379e-05, 0.0000000e+00],
       [6.3449734e-01, 0.0000000e+00, 3.6550269e-01, ..., 0.0000000e+00,
        1.3194495e-13, 0.0000000e+00],
       ...,
       [0.0000000e+00, 2.2723961e-08, 6.3296252e-31, ..., 3.5844496e-35,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 9.9995685e-01, 3.1816466e-19, ..., 1.5112999e-23,
        0.0000000e+00, 2.4313920e-24]], dtype=float32)

In [42]:
model.predict(data)[594]

array([0.0000000e+00, 7.3041981e-01, 7.8051382e-25, 7.9946952e-37,
       2.6958016e-01, 0.0000000e+00, 0.0000000e+00, 7.0400320e-27,
       0.0000000e+00, 1.8558806e-30], dtype=float32)

In [36]:
result = model.predict(data)

In [43]:
print(result[593])

[0.0000000e+00 9.9999797e-01 1.5511841e-18 2.8998798e-36 2.0642372e-06
 0.0000000e+00 7.2286073e-26 8.1994575e-20 0.0000000e+00 1.5126963e-28]


In [55]:
a = "123"

In [56]:
print(a[0])

1
