In [4]:
import read
import process
import numpy as np
data, label = read.readData()
data = process.normalization(data)

In [5]:
from keras.models import Sequential
from keras.layers import Dense, Activation
import keras

model = Sequential([
    Dense(32, input_shape=(27,)),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
label = keras.utils.to_categorical(label, num_classes=10)
model.fit(data, label, epochs=200, batch_size=32)

D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


Epoch 1/200
600/600 [==============================] - 0s 281us/step - loss: 2.2698 - acc: 0.1883
Epoch 2/200
600/600 [==============================] - 0s 53us/step - loss: 2.1781 - acc: 0.3800
Epoch 3/200
600/600 [==============================] - 0s 43us/step - loss: 2.0976 - acc: 0.3967
Epoch 4/200
600/600 [==============================] - 0s 50us/step - loss: 2.0183 - acc: 0.3983
Epoch 5/200
600/600 [==============================] - 0s 48us/step - loss: 1.9407 - acc: 0.4050
Epoch 6/200
600/600 [==============================] - 0s 55us/step - loss: 1.8651 - acc: 0.4083
Epoch 7/200
600/600 [==============================] - 0s 50us/step - loss: 1.7944 - acc: 0.4083
Epoch 8/200
600/600 [==============================] - 0s 53us/step - loss: 1.7286 - acc: 0.4083
Epoch 9/200
600/600 [==============================] - 0s 57us/step - loss: 1.6696 - acc: 0.4117
Epoch 10/200
600/600 [==============================] - 0s 60us/step - loss: 1.6182 - acc: 0.4117
Epoch 11/200
600/600 [======

600/600 [==============================] - 0s 47us/step - loss: 0.4759 - acc: 0.8350
Epoch 167/200
600/600 [==============================] - 0s 47us/step - loss: 0.4749 - acc: 0.8350
Epoch 168/200
600/600 [==============================] - 0s 47us/step - loss: 0.4732 - acc: 0.8400
Epoch 169/200
600/600 [==============================] - 0s 47us/step - loss: 0.4719 - acc: 0.8333
Epoch 170/200
600/600 [==============================] - 0s 47us/step - loss: 0.4715 - acc: 0.8333
Epoch 171/200
600/600 [==============================] - 0s 43us/step - loss: 0.4692 - acc: 0.8400
Epoch 172/200
600/600 [==============================] - 0s 48us/step - loss: 0.4690 - acc: 0.8350
Epoch 173/200
600/600 [==============================] - 0s 58us/step - loss: 0.4669 - acc: 0.8383
Epoch 174/200
600/600 [==============================] - 0s 58us/step - loss: 0.4655 - acc: 0.8367
Epoch 175/200
600/600 [==============================] - 0s 55us/step - loss: 0.4647 - acc: 0.8317
Epoch 176/200
600/600 [=

In [6]:
model.fit(data, label, epochs=200, batch_size=32)

Epoch 1/200
600/600 [==============================] - 0s 53us/step - loss: 0.4371 - acc: 0.8400
Epoch 2/200
600/600 [==============================] - 0s 45us/step - loss: 0.4365 - acc: 0.8417
Epoch 3/200
600/600 [==============================] - 0s 48us/step - loss: 0.4360 - acc: 0.8400
Epoch 4/200
600/600 [==============================] - 0s 52us/step - loss: 0.4343 - acc: 0.8383
Epoch 5/200
600/600 [==============================] - 0s 52us/step - loss: 0.4335 - acc: 0.8350
Epoch 6/200
600/600 [==============================] - 0s 57us/step - loss: 0.4328 - acc: 0.8367
Epoch 7/200
600/600 [==============================] - 0s 53us/step - loss: 0.4320 - acc: 0.8367
Epoch 8/200
600/600 [==============================] - 0s 50us/step - loss: 0.4311 - acc: 0.8367
Epoch 9/200
600/600 [==============================] - 0s 48us/step - loss: 0.4295 - acc: 0.8383
Epoch 10/200
600/600 [==============================] - 0s 52us/step - loss: 0.4287 - acc: 0.8383
Epoch 11/200
600/600 [=======

600/600 [==============================] - 0s 42us/step - loss: 0.3346 - acc: 0.8783
Epoch 168/200
600/600 [==============================] - 0s 48us/step - loss: 0.3332 - acc: 0.8733
Epoch 169/200
600/600 [==============================] - 0s 38us/step - loss: 0.3335 - acc: 0.8750
Epoch 170/200
600/600 [==============================] - 0s 42us/step - loss: 0.3330 - acc: 0.8767
Epoch 171/200
600/600 [==============================] - 0s 48us/step - loss: 0.3325 - acc: 0.8750
Epoch 172/200
600/600 [==============================] - 0s 47us/step - loss: 0.3315 - acc: 0.8733
Epoch 173/200
600/600 [==============================] - 0s 47us/step - loss: 0.3313 - acc: 0.8733
Epoch 174/200
600/600 [==============================] - 0s 43us/step - loss: 0.3320 - acc: 0.8750
Epoch 175/200
600/600 [==============================] - 0s 45us/step - loss: 0.3307 - acc: 0.8733
Epoch 176/200
600/600 [==============================] - 0s 45us/step - loss: 0.3300 - acc: 0.8717
Epoch 177/200
600/600 [=

In [3]:
result = model.predict(data)

In [4]:
print(result[599])

[1.2399084e-03 1.2634842e-02 6.1828442e-02 5.9120025e-02 2.5799184e-04
 5.9730530e-05 1.4247732e-01 7.1764742e-03 8.7904895e-04 7.1432620e-01]


In [5]:
result.shape

(600, 10)

In [6]:
import generate

In [7]:
matrix = generate.generateConfusionMatrix(result, label)

In [8]:
print(matrix)

[[1, 0, 29, 0, 0, 0, 0, 0, 0, 0], [0, 40, 0, 0, 3, 0, 0, 3, 0, 2], [0, 0, 194, 0, 0, 0, 0, 0, 9, 4], [0, 0, 0, 45, 0, 0, 0, 0, 0, 1], [0, 6, 0, 0, 33, 0, 0, 3, 0, 0], [0, 0, 0, 0, 0, 9, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 69, 0, 0, 0], [0, 12, 0, 0, 3, 0, 0, 21, 0, 1], [0, 0, 17, 0, 0, 0, 0, 0, 50, 0], [0, 0, 1, 1, 0, 0, 1, 0, 0, 41]]


In [3]:
model.fit(data, label, epochs=200, batch_size=32)

NameError: name 'model' is not defined

In [7]:
model2 = Sequential([
    Dense(32, input_shape=(27,)),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])
model2.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model2.fit(data, label, validation_split=0.3, epochs=50, batch_size=10)

Train on 420 samples, validate on 180 samples
Epoch 1/50
420/420 [==============================] - 0s 640us/step - loss: 2.1389 - acc: 0.4619 - val_loss: 2.4056 - val_acc: 0.0000e+00
Epoch 2/50
420/420 [==============================] - 0s 152us/step - loss: 1.8736 - acc: 0.5000 - val_loss: 2.5533 - val_acc: 0.0000e+00
Epoch 3/50
420/420 [==============================] - 0s 141us/step - loss: 1.6030 - acc: 0.5024 - val_loss: 2.7691 - val_acc: 0.0000e+00
Epoch 4/50
420/420 [==============================] - 0s 126us/step - loss: 1.3844 - acc: 0.5238 - val_loss: 3.0559 - val_acc: 0.0000e+00
Epoch 5/50
420/420 [==============================] - 0s 122us/step - loss: 1.2390 - acc: 0.5929 - val_loss: 3.3358 - val_acc: 0.0000e+00
Epoch 6/50
420/420 [==============================] - 0s 131us/step - loss: 1.1319 - acc: 0.6333 - val_loss: 3.6553 - val_acc: 0.0000e+00
Epoch 7/50
420/420 [==============================] - 0s 129us/step - loss: 1.0488 - acc: 0.6262 - val_loss: 3.9394 - val_acc:

In [8]:
model2.fit(data, label, validation_split=0.3, epochs=50, batch_size=10)

Train on 420 samples, validate on 180 samples
Epoch 1/50
420/420 [==============================] - 0s 138us/step - loss: 0.3546 - acc: 0.8881 - val_loss: 12.7039 - val_acc: 0.1778
Epoch 2/50
420/420 [==============================] - 0s 131us/step - loss: 0.3510 - acc: 0.8881 - val_loss: 12.7326 - val_acc: 0.1778
Epoch 3/50
420/420 [==============================] - 0s 131us/step - loss: 0.3475 - acc: 0.8857 - val_loss: 12.7487 - val_acc: 0.1778
Epoch 4/50
420/420 [==============================] - 0s 114us/step - loss: 0.3440 - acc: 0.8881 - val_loss: 12.7672 - val_acc: 0.1778
Epoch 5/50
420/420 [==============================] - 0s 122us/step - loss: 0.3419 - acc: 0.8881 - val_loss: 12.7722 - val_acc: 0.1778
Epoch 6/50
420/420 [==============================] - 0s 136us/step - loss: 0.3368 - acc: 0.8929 - val_loss: 12.8012 - val_acc: 0.1778
Epoch 7/50
420/420 [==============================] - 0s 131us/step - loss: 0.3356 - acc: 0.8881 - val_loss: 12.8016 - val_acc: 0.1778
Epoch 8/5

In [9]:
model2.fit(data, label, validation_split=0.3, epochs=50, batch_size=10)

Train on 420 samples, validate on 180 samples
Epoch 1/50
420/420 [==============================] - 0s 143us/step - loss: 0.2528 - acc: 0.8952 - val_loss: 13.0285 - val_acc: 0.1778
Epoch 2/50
420/420 [==============================] - 0s 133us/step - loss: 0.2508 - acc: 0.8952 - val_loss: 13.0434 - val_acc: 0.1778
Epoch 3/50
420/420 [==============================] - 0s 131us/step - loss: 0.2513 - acc: 0.8857 - val_loss: 13.0441 - val_acc: 0.1778
Epoch 4/50
420/420 [==============================] - 0s 112us/step - loss: 0.2498 - acc: 0.8976 - val_loss: 13.0428 - val_acc: 0.1778
Epoch 5/50
420/420 [==============================] - 0s 131us/step - loss: 0.2491 - acc: 0.8929 - val_loss: 13.0436 - val_acc: 0.1778
Epoch 6/50
420/420 [==============================] - 0s 131us/step - loss: 0.2473 - acc: 0.8952 - val_loss: 13.0402 - val_acc: 0.1778
Epoch 7/50
420/420 [==============================] - 0s 129us/step - loss: 0.2469 - acc: 0.8881 - val_loss: 13.0455 - val_acc: 0.1778
Epoch 8/5

In [10]:
model2.fit(data, label, validation_split=0.3, epochs=50, batch_size=10)

Train on 420 samples, validate on 180 samples
Epoch 1/50
420/420 [==============================] - 0s 164us/step - loss: 0.2096 - acc: 0.9024 - val_loss: 13.0180 - val_acc: 0.1778
Epoch 2/50
420/420 [==============================] - 0s 157us/step - loss: 0.2097 - acc: 0.9095 - val_loss: 13.0239 - val_acc: 0.1778
Epoch 3/50
420/420 [==============================] - 0s 131us/step - loss: 0.2095 - acc: 0.9071 - val_loss: 13.0196 - val_acc: 0.1778
Epoch 4/50
420/420 [==============================] - 0s 133us/step - loss: 0.2075 - acc: 0.9071 - val_loss: 13.0239 - val_acc: 0.1778
Epoch 5/50
420/420 [==============================] - 0s 131us/step - loss: 0.2061 - acc: 0.9095 - val_loss: 13.0294 - val_acc: 0.1778
Epoch 6/50
420/420 [==============================] - 0s 129us/step - loss: 0.2068 - acc: 0.9143 - val_loss: 13.0240 - val_acc: 0.1778
Epoch 7/50
420/420 [==============================] - 0s 129us/step - loss: 0.2059 - acc: 0.9071 - val_loss: 13.0155 - val_acc: 0.1778
Epoch 8/5

In [11]:
import read3

In [12]:
tr_data, tr_label, te_data, te_label = read3.readData()

In [13]:
train_label = keras.utils.to_categorical(tr_label, num_classes=10)
test_label = keras.utils.to_categorical(te_label, num_classes=10)

In [27]:
model5 = Sequential([
    Dense(32, input_shape=(27,)),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])
model5.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])


In [23]:
model4.fit(tr_data, train_label, epochs=100,validation_data=(te_data,test_label), batch_size=10)

Train on 415 samples, validate on 175 samples
Epoch 1/100
415/415 [==============================] - 0s 159us/step - loss: 1.2250 - acc: 0.8940 - val_loss: 1.7171 - val_acc: 0.7943
Epoch 2/100
415/415 [==============================] - 0s 137us/step - loss: 1.2271 - acc: 0.8940 - val_loss: 1.6609 - val_acc: 0.8000
Epoch 3/100
415/415 [==============================] - 0s 137us/step - loss: 1.2228 - acc: 0.8964 - val_loss: 1.6985 - val_acc: 0.7943
Epoch 4/100
415/415 [==============================] - 0s 137us/step - loss: 1.2258 - acc: 0.8916 - val_loss: 1.6662 - val_acc: 0.7829
Epoch 5/100
415/415 [==============================] - 0s 162us/step - loss: 1.2150 - acc: 0.9012 - val_loss: 1.7243 - val_acc: 0.7829
Epoch 6/100
415/415 [==============================] - 0s 145us/step - loss: 1.2224 - acc: 0.8964 - val_loss: 1.7012 - val_acc: 0.7943
Epoch 7/100
415/415 [==============================] - 0s 121us/step - loss: 1.2206 - acc: 0.8867 - val_loss: 1.6713 - val_acc: 0.7943
Epoch 8/1

Epoch 61/100
415/415 [==============================] - 0s 183us/step - loss: 1.1629 - acc: 0.9253 - val_loss: 1.9339 - val_acc: 0.7886
Epoch 62/100
415/415 [==============================] - 0s 169us/step - loss: 1.1719 - acc: 0.9181 - val_loss: 1.8444 - val_acc: 0.7886
Epoch 63/100
415/415 [==============================] - 0s 149us/step - loss: 1.1642 - acc: 0.9253 - val_loss: 1.9108 - val_acc: 0.7829
Epoch 64/100
415/415 [==============================] - 0s 135us/step - loss: 1.1660 - acc: 0.9205 - val_loss: 1.9181 - val_acc: 0.8000
Epoch 65/100
415/415 [==============================] - 0s 133us/step - loss: 1.1650 - acc: 0.9205 - val_loss: 1.8942 - val_acc: 0.8000
Epoch 66/100
415/415 [==============================] - 0s 133us/step - loss: 1.1668 - acc: 0.9253 - val_loss: 1.8847 - val_acc: 0.7943
Epoch 67/100
415/415 [==============================] - 0s 140us/step - loss: 1.1635 - acc: 0.9253 - val_loss: 1.8601 - val_acc: 0.7886
Epoch 68/100
415/415 [==========================

In [30]:
model5.fit(data, label, epochs=100,validation_split=0.33, batch_size=10)

Train on 401 samples, validate on 199 samples
Epoch 1/100
401/401 [==============================] - 0s 765us/step - loss: 2.1355 - acc: 0.3791 - val_loss: 2.5289 - val_acc: 0.0000e+00
Epoch 2/100
401/401 [==============================] - 0s 138us/step - loss: 1.8808 - acc: 0.6309 - val_loss: 2.6994 - val_acc: 0.0000e+00
Epoch 3/100
401/401 [==============================] - 0s 128us/step - loss: 1.6249 - acc: 0.6334 - val_loss: 2.9172 - val_acc: 0.0000e+00
Epoch 4/100
401/401 [==============================] - 0s 142us/step - loss: 1.3969 - acc: 0.6584 - val_loss: 3.2215 - val_acc: 0.0000e+00
Epoch 5/100
401/401 [==============================] - 0s 145us/step - loss: 1.2108 - acc: 0.6484 - val_loss: 3.5659 - val_acc: 0.0000e+00
Epoch 6/100
401/401 [==============================] - 0s 145us/step - loss: 1.0951 - acc: 0.6434 - val_loss: 3.9074 - val_acc: 0.0000e+00
Epoch 7/100
401/401 [==============================] - 0s 150us/step - loss: 1.0182 - acc: 0.6683 - val_loss: 4.2462 - v

In [26]:
data, label = read.readData()

In [29]:
data = process.normalization(data)
label = keras.utils.to_categorical(label, num_classes=10)


In [1]:
import numpy

In [2]:
numpy.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
aa = numpy.array([1,2,3,4,5,6])

In [4]:
aa[[1,2]]

array([2, 3])

In [6]:
aa = numpy.array([[1,2],[3,4],[5,6]])
aa[[1,2]]

array([[3, 4],
       [5, 6]])

In [7]:
aa[1,2]

IndexError: index 2 is out of bounds for axis 1 with size 2