In [1]:
import read

In [2]:
read_data, no_act, map_act = read.readData()

In [3]:
print(no_act)

{'Bed_to_toilet': 30, 'Breakfast': 48, 'Bed': 207, 'C_work': 46, 'Dinner': 42, 'Laundry': 10, 'Leave_home': 69, 'Lunch': 37, 'Night_wandering': 67, 'R_medicine': 44}


In [44]:
read_data

AttributeError: 'dict' object has no attribute 'shape'

In [5]:
print(read_data)

{'Bed_to_toilet': [[0, 0, 0, 0, 8, 0, 2, 2, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 6, 1, 1, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 2, 0, 0, 21, 2, 4, 5, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 2, 1, 0, 2, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 2, 0, 0, 9, 2, 6, 1, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 2, 0, 0, 11, 2, 6, 2, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 7, 0, 4, 1, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 5, 0, 3, 1, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 2, 0, 0, 12, 2, 6, 2, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 2, 0, 0, 20, 2, 9, 4, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 2, 2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 2, 1, 0, 7, 2, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [14]:
X_train = []
X_test  = []
for i in range(10):
    for j in range(int(0.7*no_act[map_act[i]])):
        X_train.append(read_data[map_act[i]][j])
    for k in range(int(0.7*no_act[map_act[i]])+1, no_act[map_act[i]]):
        X_test.append(read_data[map_act[i]][j])
   

In [16]:
X_train = X_train.reshape(X_train.shape[0], 1, 28)

AttributeError: 'list' object has no attribute 'reshape'

In [17]:
import numpy as np

In [18]:
array = np.array(X_train)

In [24]:
array = array.reshape(array.shape[0], 27, 1)

In [26]:
array = array.reshape(array.shape[0], 27)

In [27]:
array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 2, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [28]:
X_train = np.array(X_train)

In [29]:
X_test = np.array(X_test)

In [30]:
X_train = []
X_test  = []
for i in range(10):
    for j in range(int(0.7*no_act[map_act[i]])):
        X_train.append(read_data[map_act[i]][j])
        y_train.append(i)
    for k in range(int(0.7*no_act[map_act[i]])+1, no_act[map_act[i]]):
        X_test.append(read_data[map_act[i]][j])
        y_test.append(i)
 

NameError: name 'y_train' is not defined

In [31]:
X_train = []
y_train = []
X_test  = []
y_test  = []
for i in range(10):
    for j in range(int(0.7*no_act[map_act[i]])):
        X_train.append(read_data[map_act[i]][j])
        y_train.append(i)
    for k in range(int(0.7*no_act[map_act[i]])+1, no_act[map_act[i]]):
        X_test.append(read_data[map_act[i]][j])
        y_test.append(i)
 

In [34]:
X_train = np.array(X_train)
X_test  = np.array(X_test)

In [35]:
Y_train = np_utils.to_categorical(y_train, 10)

NameError: name 'np_utils' is not defined

In [36]:
from keras.utils import np_utils

D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [37]:
Y_train = np_utils.to_categorical(y_train, 10)
Y_test  = np_utils.to_categorical(y_test,  10)

In [45]:
Y_train.shape

(415, 10)

In [41]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 2, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [42]:
print(X_train.shape)

(415, 27)


In [43]:
print(X_test.shape)

(175, 27)


In [46]:
X_train[0]

array([0, 0, 0, 0, 8, 0, 2, 2, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])