In [1]:
import read2

In [1]:
import process

In [3]:
data, label = read2.readData()

In [6]:
data.shape

(1513, 18)

In [7]:
label.shape

(1513, 10, 10)

In [8]:
data, label = read2.readData()

In [9]:
print(label)

[0 0 0 ... 9 9 9]


In [11]:
label = keras.utils.to_categorical(label, num_classes=10)

In [12]:
label.shape

(1513, 10)

In [13]:
model.fit(data, label, epochs=200, batch_size=32)

Epoch 1/200
1513/1513 [==============================] - 0s 246us/step - loss: 4.7100 - acc: 0.2558
Epoch 2/200
1513/1513 [==============================] - 0s 56us/step - loss: 1.9825 - acc: 0.6021
Epoch 3/200
1513/1513 [==============================] - 0s 53us/step - loss: 1.6789 - acc: 0.6728
Epoch 4/200
1513/1513 [==============================] - 0s 58us/step - loss: 1.4610 - acc: 0.7085
Epoch 5/200
1513/1513 [==============================] - 0s 55us/step - loss: 1.2975 - acc: 0.7191
Epoch 6/200
1513/1513 [==============================] - 0s 74us/step - loss: 1.1929 - acc: 0.7422
Epoch 7/200
1513/1513 [==============================] - 0s 52us/step - loss: 1.1132 - acc: 0.7462
Epoch 8/200
1513/1513 [==============================] - 0s 57us/step - loss: 1.0387 - acc: 0.7594
Epoch 9/200
1513/1513 [==============================] - 0s 57us/step - loss: 0.9901 - acc: 0.7627
Epoch 10/200
1513/1513 [==============================] - 0s 55us/step - loss: 0.9343 - acc: 0.7687
Epoch 11

1513/1513 [==============================] - 0s 51us/step - loss: 0.3706 - acc: 0.9022
Epoch 163/200
1513/1513 [==============================] - 0s 61us/step - loss: 0.3685 - acc: 0.8949
Epoch 164/200
1513/1513 [==============================] - 0s 60us/step - loss: 0.3607 - acc: 0.9015
Epoch 165/200
1513/1513 [==============================] - 0s 71us/step - loss: 0.3709 - acc: 0.9002
Epoch 166/200
1513/1513 [==============================] - 0s 63us/step - loss: 0.3664 - acc: 0.9035
Epoch 167/200
1513/1513 [==============================] - 0s 58us/step - loss: 0.3642 - acc: 0.9015
Epoch 168/200
1513/1513 [==============================] - 0s 59us/step - loss: 0.3609 - acc: 0.9028
Epoch 169/200
1513/1513 [==============================] - 0s 63us/step - loss: 0.3557 - acc: 0.9009
Epoch 170/200
1513/1513 [==============================] - 0s 61us/step - loss: 0.3649 - acc: 0.9002
Epoch 171/200
1513/1513 [==============================] - 0s 77us/step - loss: 0.3684 - acc: 0.9035
Epoc

In [14]:
model.fit(data, label, epochs=50, batch_size=32)

Epoch 1/50
1513/1513 [==============================] - 0s 48us/step - loss: 0.3317 - acc: 0.9048
Epoch 2/50
1513/1513 [==============================] - 0s 44us/step - loss: 0.3414 - acc: 0.9035
Epoch 3/50
1513/1513 [==============================] - 0s 59us/step - loss: 0.3385 - acc: 0.9061
Epoch 4/50
1513/1513 [==============================] - 0s 60us/step - loss: 0.3365 - acc: 0.9075
Epoch 5/50
1513/1513 [==============================] - 0s 49us/step - loss: 0.3364 - acc: 0.9075
Epoch 6/50
1513/1513 [==============================] - 0s 54us/step - loss: 0.3414 - acc: 0.9068
Epoch 7/50
1513/1513 [==============================] - 0s 54us/step - loss: 0.3453 - acc: 0.9022
Epoch 8/50
1513/1513 [==============================] - 0s 56us/step - loss: 0.3342 - acc: 0.9121
Epoch 9/50
1513/1513 [==============================] - 0s 57us/step - loss: 0.3364 - acc: 0.9068
Epoch 10/50
1513/1513 [==============================] - 0s 63us/step - loss: 0.3369 - acc: 0.8982
Epoch 11/50
1513/15

In [15]:
model.fit(data, label, epochs=200, batch_size=32)

Epoch 1/200
1513/1513 [==============================] - 0s 46us/step - loss: 0.3147 - acc: 0.9121
Epoch 2/200
1513/1513 [==============================] - 0s 42us/step - loss: 0.3275 - acc: 0.9068
Epoch 3/200
1513/1513 [==============================] - 0s 58us/step - loss: 0.3278 - acc: 0.9095
Epoch 4/200
1513/1513 [==============================] - 0s 60us/step - loss: 0.3184 - acc: 0.9101
Epoch 5/200
1513/1513 [==============================] - 0s 76us/step - loss: 0.3158 - acc: 0.9088
Epoch 6/200
1513/1513 [==============================] - 0s 52us/step - loss: 0.3094 - acc: 0.9121
Epoch 7/200
1513/1513 [==============================] - 0s 52us/step - loss: 0.3234 - acc: 0.9068
Epoch 8/200
1513/1513 [==============================] - 0s 53us/step - loss: 0.3195 - acc: 0.9134
Epoch 9/200
1513/1513 [==============================] - 0s 49us/step - loss: 0.3170 - acc: 0.9095
Epoch 10/200
1513/1513 [==============================] - 0s 54us/step - loss: 0.3160 - acc: 0.9187
Epoch 11/

1513/1513 [==============================] - 0s 55us/step - loss: 0.2950 - acc: 0.9194
Epoch 84/200
1513/1513 [==============================] - 0s 61us/step - loss: 0.2869 - acc: 0.9194
Epoch 85/200
1513/1513 [==============================] - 0s 67us/step - loss: 0.2931 - acc: 0.9174
Epoch 86/200
1513/1513 [==============================] - 0s 65us/step - loss: 0.2919 - acc: 0.9187
Epoch 87/200
1513/1513 [==============================] - 0s 65us/step - loss: 0.2904 - acc: 0.9161
Epoch 88/200
1513/1513 [==============================] - 0s 52us/step - loss: 0.2849 - acc: 0.9220
Epoch 89/200
1513/1513 [==============================] - 0s 77us/step - loss: 0.2913 - acc: 0.9240
Epoch 90/200
1513/1513 [==============================] - 0s 58us/step - loss: 0.2937 - acc: 0.9220
Epoch 91/200
1513/1513 [==============================] - 0s 102us/step - loss: 0.2926 - acc: 0.9220
Epoch 92/200
1513/1513 [==============================] - 0s 61us/step - loss: 0.2935 - acc: 0.9114
Epoch 93/200

In [16]:
model.fit(data, label, epochs=200, batch_size=32)

Epoch 1/200
1513/1513 [==============================] - 0s 47us/step - loss: 0.2587 - acc: 0.9372
Epoch 2/200
1513/1513 [==============================] - 0s 40us/step - loss: 0.2678 - acc: 0.9293
Epoch 3/200
1513/1513 [==============================] - 0s 53us/step - loss: 0.2607 - acc: 0.9326
Epoch 4/200
1513/1513 [==============================] - 0s 44us/step - loss: 0.2660 - acc: 0.9266
Epoch 5/200
1513/1513 [==============================] - 0s 49us/step - loss: 0.2631 - acc: 0.9339
Epoch 6/200
1513/1513 [==============================] - 0s 51us/step - loss: 0.2626 - acc: 0.9352
Epoch 7/200
1513/1513 [==============================] - 0s 53us/step - loss: 0.2661 - acc: 0.9306
Epoch 8/200
1513/1513 [==============================] - 0s 46us/step - loss: 0.2619 - acc: 0.9319
Epoch 9/200
1513/1513 [==============================] - 0s 50us/step - loss: 0.2612 - acc: 0.9319
Epoch 10/200
1513/1513 [==============================] - 0s 52us/step - loss: 0.2680 - acc: 0.9286
Epoch 11/

1513/1513 [==============================] - 0s 48us/step - loss: 0.2380 - acc: 0.9399
Epoch 163/200
1513/1513 [==============================] - 0s 51us/step - loss: 0.2448 - acc: 0.9372
Epoch 164/200
1513/1513 [==============================] - 0s 46us/step - loss: 0.2423 - acc: 0.9372
Epoch 165/200
1513/1513 [==============================] - 0s 48us/step - loss: 0.2443 - acc: 0.9392
Epoch 166/200
1513/1513 [==============================] - 0s 46us/step - loss: 0.2365 - acc: 0.9385
Epoch 167/200
1513/1513 [==============================] - 0s 45us/step - loss: 0.2432 - acc: 0.9405
Epoch 168/200
1513/1513 [==============================] - 0s 49us/step - loss: 0.2386 - acc: 0.9399
Epoch 169/200
1513/1513 [==============================] - 0s 46us/step - loss: 0.2455 - acc: 0.9326
Epoch 170/200
1513/1513 [==============================] - 0s 45us/step - loss: 0.2432 - acc: 0.9372
Epoch 171/200
1513/1513 [==============================] - 0s 49us/step - loss: 0.2456 - acc: 0.9372
Epoc

In [6]:
import importlib

In [10]:
import read2

D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [15]:
train_data, train_label, test_data, test_label = read2.readData()

In [14]:
importlib.reload(read2)

<module 'read2' from 'C:\\Users\\Jay\\Desktop\\capstone\\read2.py'>

In [16]:
import model

In [17]:
train_data.shape

(1006, 18)

In [18]:
model = model.create_model(shape=18)

In [19]:
model.fit(train_data, train_label, epochs=200, validation_data=(test_data, test_label), batch_size=10)

Train on 1006 samples, validate on 497 samples
Epoch 1/200
1006/1006 [==============================] - 0s 268us/step - loss: 3.5264 - acc: 0.5656 - val_loss: 2.5726 - val_acc: 0.6378
Epoch 2/200
1006/1006 [==============================] - 0s 125us/step - loss: 2.0496 - acc: 0.6431 - val_loss: 1.8263 - val_acc: 0.6640
Epoch 3/200
1006/1006 [==============================] - 0s 125us/step - loss: 1.6779 - acc: 0.6799 - val_loss: 1.5373 - val_acc: 0.7022
Epoch 4/200
1006/1006 [==============================] - 0s 126us/step - loss: 1.4258 - acc: 0.7068 - val_loss: 1.3381 - val_acc: 0.6982
Epoch 5/200
1006/1006 [==============================] - 0s 116us/step - loss: 1.2823 - acc: 0.7217 - val_loss: 1.2937 - val_acc: 0.7183
Epoch 6/200
1006/1006 [==============================] - 0s 123us/step - loss: 1.2243 - acc: 0.7316 - val_loss: 1.1775 - val_acc: 0.7465
Epoch 7/200
1006/1006 [==============================] - 0s 128us/step - loss: 1.1586 - acc: 0.7485 - val_loss: 1.1914 - val_acc: 0

1006/1006 [==============================] - 0s 155us/step - loss: 0.4803 - acc: 0.8728 - val_loss: 0.8549 - val_acc: 0.8048
Epoch 61/200
1006/1006 [==============================] - 0s 111us/step - loss: 0.4774 - acc: 0.8678 - val_loss: 0.8375 - val_acc: 0.8109
Epoch 62/200
1006/1006 [==============================] - 0s 105us/step - loss: 0.4644 - acc: 0.8777 - val_loss: 0.8874 - val_acc: 0.8169
Epoch 63/200
1006/1006 [==============================] - 0s 112us/step - loss: 0.4865 - acc: 0.8708 - val_loss: 0.8460 - val_acc: 0.8109
Epoch 64/200
1006/1006 [==============================] - 0s 119us/step - loss: 0.4625 - acc: 0.8797 - val_loss: 0.8427 - val_acc: 0.8189
Epoch 65/200
1006/1006 [==============================] - 0s 115us/step - loss: 0.4711 - acc: 0.8757 - val_loss: 0.8906 - val_acc: 0.8068
Epoch 66/200
1006/1006 [==============================] - 0s 115us/step - loss: 0.4600 - acc: 0.8767 - val_loss: 0.9112 - val_acc: 0.8129
Epoch 67/200
1006/1006 [=======================

Epoch 178/200
1006/1006 [==============================] - 0s 171us/step - loss: 0.3377 - acc: 0.9175 - val_loss: 1.0511 - val_acc: 0.8068
Epoch 179/200
1006/1006 [==============================] - 0s 160us/step - loss: 0.3293 - acc: 0.9165 - val_loss: 1.0670 - val_acc: 0.8068
Epoch 180/200
1006/1006 [==============================] - 0s 148us/step - loss: 0.3207 - acc: 0.9175 - val_loss: 1.0714 - val_acc: 0.8048
Epoch 181/200
1006/1006 [==============================] - 0s 111us/step - loss: 0.3266 - acc: 0.9235 - val_loss: 1.0833 - val_acc: 0.8109
Epoch 182/200
1006/1006 [==============================] - 0s 113us/step - loss: 0.3306 - acc: 0.9145 - val_loss: 1.0663 - val_acc: 0.8129
Epoch 183/200
1006/1006 [==============================] - 0s 126us/step - loss: 0.3275 - acc: 0.9264 - val_loss: 1.1202 - val_acc: 0.8089
Epoch 184/200
1006/1006 [==============================] - 0s 142us/step - loss: 0.3185 - acc: 0.9245 - val_loss: 1.0863 - val_acc: 0.8129
Epoch 185/200
1006/1006 [==

In [1]:
importlib.reload(read2)

NameError: name 'importlib' is not defined

In [2]:
from importlib import reload

In [3]:
reload(read2)

NameError: name 'read2' is not defined

In [5]:
import read2

D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [6]:
data, label = read2.readData()

In [7]:
import process

In [9]:
data = process.normalization(data)

In [10]:
print(data[0])

[0.01098901 0.00544959 0.28139535 0.03761062 0.10344828 0.07142857
 0.003125   0.00145985 0.00451128 0.         0.         0.
 0.         0.15269461 0.28181818 0.11842105 0.         0.        ]


In [11]:
import k_fold

In [12]:
k_fold.cross_validate(data, label)

ValueError: Error when checking input: expected dense_1_input to have shape (27,) but got array with shape (18,)

In [16]:
k_fold.cross_validate(data, label, sensor_num=18)

Train on 1006 samples, validate on 507 samples
Epoch 1/200
1006/1006 [==============================] - 0s 277us/step - loss: 2.1455 - acc: 0.3748 - val_loss: 1.9927 - val_acc: 0.3432
Epoch 2/200
1006/1006 [==============================] - 0s 134us/step - loss: 1.8639 - acc: 0.3579 - val_loss: 1.7619 - val_acc: 0.3728
Epoch 3/200
1006/1006 [==============================] - 0s 128us/step - loss: 1.6980 - acc: 0.5070 - val_loss: 1.6567 - val_acc: 0.5819
Epoch 4/200
1006/1006 [==============================] - 0s 108us/step - loss: 1.6158 - acc: 0.5447 - val_loss: 1.5914 - val_acc: 0.4990
Epoch 5/200
1006/1006 [==============================] - 0s 110us/step - loss: 1.5551 - acc: 0.4901 - val_loss: 1.5337 - val_acc: 0.5128
Epoch 6/200
1006/1006 [==============================] - 0s 125us/step - loss: 1.4995 - acc: 0.5000 - val_loss: 1.4815 - val_acc: 0.5306
Epoch 7/200
1006/1006 [==============================] - 0s 131us/step - loss: 1.4483 - acc: 0.5169 - val_loss: 1.4324 - val_acc: 0

1006/1006 [==============================] - 0s 134us/step - loss: 0.6995 - acc: 0.7793 - val_loss: 0.7634 - val_acc: 0.7791
Epoch 61/200
1006/1006 [==============================] - 0s 133us/step - loss: 0.6956 - acc: 0.7793 - val_loss: 0.7606 - val_acc: 0.7732
Epoch 62/200
1006/1006 [==============================] - 0s 111us/step - loss: 0.6928 - acc: 0.7763 - val_loss: 0.7591 - val_acc: 0.7732
Epoch 63/200
1006/1006 [==============================] - 0s 123us/step - loss: 0.6887 - acc: 0.7744 - val_loss: 0.7564 - val_acc: 0.7791
Epoch 64/200
1006/1006 [==============================] - 0s 113us/step - loss: 0.6853 - acc: 0.7763 - val_loss: 0.7563 - val_acc: 0.7811
Epoch 65/200
1006/1006 [==============================] - 0s 108us/step - loss: 0.6828 - acc: 0.7823 - val_loss: 0.7524 - val_acc: 0.7751
Epoch 66/200
1006/1006 [==============================] - 0s 113us/step - loss: 0.6800 - acc: 0.7813 - val_loss: 0.7510 - val_acc: 0.7890
Epoch 67/200
1006/1006 [=======================

Epoch 178/200
1006/1006 [==============================] - 0s 119us/step - loss: 0.5406 - acc: 0.8181 - val_loss: 0.6369 - val_acc: 0.8008
Epoch 179/200
1006/1006 [==============================] - 0s 113us/step - loss: 0.5400 - acc: 0.8191 - val_loss: 0.6355 - val_acc: 0.8028
Epoch 180/200
1006/1006 [==============================] - 0s 134us/step - loss: 0.5388 - acc: 0.8191 - val_loss: 0.6345 - val_acc: 0.8028
Epoch 181/200
1006/1006 [==============================] - 0s 149us/step - loss: 0.5395 - acc: 0.8211 - val_loss: 0.6350 - val_acc: 0.8008
Epoch 182/200
1006/1006 [==============================] - 0s 136us/step - loss: 0.5383 - acc: 0.8171 - val_loss: 0.6352 - val_acc: 0.7968
Epoch 183/200
1006/1006 [==============================] - 0s 125us/step - loss: 0.5373 - acc: 0.8191 - val_loss: 0.6349 - val_acc: 0.7988
Epoch 184/200
1006/1006 [==============================] - 0s 156us/step - loss: 0.5367 - acc: 0.8201 - val_loss: 0.6359 - val_acc: 0.7988
Epoch 185/200
1006/1006 [==

Epoch 37/200
1007/1007 [==============================] - 0s 134us/step - loss: 0.5363 - acc: 0.8163 - val_loss: 0.5534 - val_acc: 0.8281
Epoch 38/200
1007/1007 [==============================] - 0s 143us/step - loss: 0.5358 - acc: 0.8133 - val_loss: 0.5564 - val_acc: 0.8202
Epoch 39/200
1007/1007 [==============================] - 0s 144us/step - loss: 0.5362 - acc: 0.8173 - val_loss: 0.5590 - val_acc: 0.8162
Epoch 40/200
1007/1007 [==============================] - 0s 111us/step - loss: 0.5355 - acc: 0.8193 - val_loss: 0.5609 - val_acc: 0.8221
Epoch 41/200
1007/1007 [==============================] - 0s 113us/step - loss: 0.5357 - acc: 0.8153 - val_loss: 0.5562 - val_acc: 0.8221
Epoch 42/200
1007/1007 [==============================] - 0s 147us/step - loss: 0.5350 - acc: 0.8173 - val_loss: 0.5568 - val_acc: 0.8221
Epoch 43/200
1007/1007 [==============================] - 0s 144us/step - loss: 0.5342 - acc: 0.8133 - val_loss: 0.5545 - val_acc: 0.8241
Epoch 44/200
1007/1007 [==========

1007/1007 [==============================] - 0s 147us/step - loss: 0.5038 - acc: 0.8242 - val_loss: 0.5639 - val_acc: 0.8123
Epoch 97/200
1007/1007 [==============================] - 0s 113us/step - loss: 0.5037 - acc: 0.8252 - val_loss: 0.5650 - val_acc: 0.8123
Epoch 98/200
1007/1007 [==============================] - 0s 145us/step - loss: 0.5050 - acc: 0.8232 - val_loss: 0.5631 - val_acc: 0.8142
Epoch 99/200
1007/1007 [==============================] - 0s 147us/step - loss: 0.5032 - acc: 0.8213 - val_loss: 0.5605 - val_acc: 0.8182
Epoch 100/200
1007/1007 [==============================] - 0s 133us/step - loss: 0.5030 - acc: 0.8282 - val_loss: 0.5615 - val_acc: 0.8202
Epoch 101/200
1007/1007 [==============================] - 0s 106us/step - loss: 0.5033 - acc: 0.8213 - val_loss: 0.5616 - val_acc: 0.8162
Epoch 102/200
1007/1007 [==============================] - 0s 124us/step - loss: 0.5017 - acc: 0.8262 - val_loss: 0.5599 - val_acc: 0.8261
Epoch 103/200
1007/1007 [===================

1007/1007 [==============================] - 0s 152us/step - loss: 0.4800 - acc: 0.8332 - val_loss: 0.5634 - val_acc: 0.8123
Epoch 156/200
1007/1007 [==============================] - 0s 148us/step - loss: 0.4800 - acc: 0.8312 - val_loss: 0.5615 - val_acc: 0.8281
Epoch 157/200
1007/1007 [==============================] - 0s 143us/step - loss: 0.4782 - acc: 0.8391 - val_loss: 0.5642 - val_acc: 0.8182
Epoch 158/200
1007/1007 [==============================] - 0s 107us/step - loss: 0.4776 - acc: 0.8332 - val_loss: 0.5630 - val_acc: 0.8241
Epoch 159/200
1007/1007 [==============================] - 0s 113us/step - loss: 0.4788 - acc: 0.8302 - val_loss: 0.5597 - val_acc: 0.8320
Epoch 160/200
1007/1007 [==============================] - 0s 108us/step - loss: 0.4766 - acc: 0.8352 - val_loss: 0.5638 - val_acc: 0.8202
Epoch 161/200
1007/1007 [==============================] - 0s 112us/step - loss: 0.4777 - acc: 0.8332 - val_loss: 0.5606 - val_acc: 0.8281
Epoch 162/200
1007/1007 [================

Epoch 14/200
1013/1013 [==============================] - 0s 108us/step - loss: 0.5010 - acc: 0.8371 - val_loss: 0.4526 - val_acc: 0.8440
Epoch 15/200
1013/1013 [==============================] - 0s 107us/step - loss: 0.5007 - acc: 0.8381 - val_loss: 0.4528 - val_acc: 0.8380
Epoch 16/200
1013/1013 [==============================] - 0s 106us/step - loss: 0.4973 - acc: 0.8391 - val_loss: 0.4565 - val_acc: 0.8380
Epoch 17/200
1013/1013 [==============================] - 0s 110us/step - loss: 0.4985 - acc: 0.8421 - val_loss: 0.4548 - val_acc: 0.8420
Epoch 18/200
1013/1013 [==============================] - 0s 106us/step - loss: 0.4976 - acc: 0.8322 - val_loss: 0.4564 - val_acc: 0.8440
Epoch 19/200
1013/1013 [==============================] - 0s 111us/step - loss: 0.4971 - acc: 0.8401 - val_loss: 0.4575 - val_acc: 0.8380
Epoch 20/200
1013/1013 [==============================] - 0s 101us/step - loss: 0.4960 - acc: 0.8381 - val_loss: 0.4588 - val_acc: 0.8440
Epoch 21/200
1013/1013 [==========

1013/1013 [==============================] - 0s 112us/step - loss: 0.4543 - acc: 0.8598 - val_loss: 0.5234 - val_acc: 0.8420
Epoch 133/200
1013/1013 [==============================] - 0s 105us/step - loss: 0.4542 - acc: 0.8588 - val_loss: 0.5238 - val_acc: 0.8320
Epoch 134/200
1013/1013 [==============================] - 0s 108us/step - loss: 0.4531 - acc: 0.8588 - val_loss: 0.5255 - val_acc: 0.8340
Epoch 135/200
1013/1013 [==============================] - 0s 107us/step - loss: 0.4534 - acc: 0.8529 - val_loss: 0.5256 - val_acc: 0.8340
Epoch 136/200
1013/1013 [==============================] - 0s 109us/step - loss: 0.4526 - acc: 0.8559 - val_loss: 0.5266 - val_acc: 0.8360
Epoch 137/200
1013/1013 [==============================] - 0s 106us/step - loss: 0.4531 - acc: 0.8529 - val_loss: 0.5240 - val_acc: 0.8400
Epoch 138/200
1013/1013 [==============================] - 0s 113us/step - loss: 0.4530 - acc: 0.8559 - val_loss: 0.5268 - val_acc: 0.8380
Epoch 139/200
1013/1013 [================

1013/1013 [==============================] - 0s 124us/step - loss: 0.4411 - acc: 0.8559 - val_loss: 0.5388 - val_acc: 0.8420
Epoch 192/200
1013/1013 [==============================] - 0s 106us/step - loss: 0.4416 - acc: 0.8598 - val_loss: 0.5372 - val_acc: 0.8400
Epoch 193/200
1013/1013 [==============================] - 0s 110us/step - loss: 0.4399 - acc: 0.8598 - val_loss: 0.5392 - val_acc: 0.8380
Epoch 194/200
1013/1013 [==============================] - 0s 104us/step - loss: 0.4406 - acc: 0.8539 - val_loss: 0.5396 - val_acc: 0.8460
Epoch 195/200
1013/1013 [==============================] - 0s 114us/step - loss: 0.4423 - acc: 0.8539 - val_loss: 0.5413 - val_acc: 0.8400
Epoch 196/200
1013/1013 [==============================] - 0s 105us/step - loss: 0.4401 - acc: 0.8608 - val_loss: 0.5423 - val_acc: 0.8340
Epoch 197/200
1013/1013 [==============================] - 0s 106us/step - loss: 0.4401 - acc: 0.8529 - val_loss: 0.5406 - val_acc: 0.8360
Epoch 198/200
1013/1013 [================

In [15]:
reload(k_fold)

<module 'k_fold' from 'C:\\Users\\Jay\\Desktop\\capstone\\k_fold.py'>

In [1]:
import read

ModuleNotFoundError: No module named 'read'

In [2]:
import module/read

SyntaxError: invalid syntax (<ipython-input-2-39304553e64d>, line 1)

In [6]:
exec("/modules/read.py")

SyntaxError: invalid syntax (<string>, line 1)

In [7]:
import os, sys

In [8]:
sys.path.append(os.path.abspath("modules/read.py"))

In [9]:
import read

ModuleNotFoundError: No module named 'read'

In [13]:
sys.path.append('../read.py')

In [15]:
import read

ModuleNotFoundError: No module named 'read'

In [16]:
import read

In [20]:
data, label = read.readData()

In [18]:
import importlib

In [19]:
importlib.reload(read)

<module 'read' from 'C:\\Users\\Jay\\Desktop\\capstone\\Neural-Network-Classifier\\read.py'>

In [21]:
print(data)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [22]:
print(data[599])

[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 5 2 1 5 0 0 0]
